import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../planner/models.dart';

/// Holds the plan generated by [PlannerGateway] for the current user.
/// Local-only (no backend), persisted as JSON — same pattern as the other
/// controllers in lib/state/.
class PlanController extends ChangeNotifier {
  static const _kPlan = 'generated_plan_json';

  GeneratedPlan? plan;

  bool get hasPlan => plan != null;

  Future<void> load() async {
    final prefs = await SharedPreferences.getInstance();
    final raw = prefs.getString(_kPlan);
    if (raw != null) {
      try {
        plan = GeneratedPlan.fromJson(jsonDecode(raw) as Map<String, dynamic>);
      } catch (_) {
        // Corrupted/old-shape cache — fall through to no plan, user redoes
        // the survey next time _AppGate checks hasPlan.
        plan = null;
      }
    }
    notifyListeners();
  }

  Future<void> save(GeneratedPlan value) async {
    plan = value;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_kPlan, jsonEncode(value.toJson()));
  }
}
