import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../planner/check_in.dart';
import '../planner/models.dart';

/// Holds the plan generated by [PlannerGateway] for the current user.
/// Local-only (no backend), persisted as JSON — same pattern as the other
/// controllers in lib/state/.
class PlanController extends ChangeNotifier {
  static const _kPlan = 'generated_plan_json';
  static const _kCheckPromptedAt = 'check_prompt_generated_at';
  static const _kCheckPromptedWeek = 'check_prompt_week';

  GeneratedPlan? plan;
  String? checkPromptedAt;
  int checkPromptedWeek = 0;

  bool get hasPlan => plan != null;

  bool get needsCheckInPrompt {
    final current = plan;
    if (current == null) return false;
    return shouldPromptCheckIn(
      plan: current,
      promptedGeneratedAt: checkPromptedAt,
      promptedWeek: checkPromptedWeek,
    );
  }

  Future<void> load() async {
    final prefs = await SharedPreferences.getInstance();
    final raw = prefs.getString(_kPlan);
    if (raw != null) {
      try {
        plan = GeneratedPlan.fromJson(jsonDecode(raw) as Map<String, dynamic>);
      } catch (_) {
        // Corrupted/old-shape cache — fall through to no plan, user redoes
        // the survey next time _AppGate checks hasPlan.
        plan = null;
      }
    }
    checkPromptedAt = prefs.getString(_kCheckPromptedAt);
    checkPromptedWeek = prefs.getInt(_kCheckPromptedWeek) ?? 0;
    notifyListeners();
  }

  Future<void> markCheckPrompted({required DateTime generatedAt, required int week}) async {
    checkPromptedAt = generatedAt.toIso8601String();
    checkPromptedWeek = week;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_kCheckPromptedAt, checkPromptedAt!);
    await prefs.setInt(_kCheckPromptedWeek, week);
  }

  Future<void> save(GeneratedPlan value) async {
    plan = value;
    checkPromptedAt = null;
    checkPromptedWeek = 0;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_kPlan, jsonEncode(value.toJson()));
    await prefs.remove(_kCheckPromptedAt);
    await prefs.remove(_kCheckPromptedWeek);
  }
}
