import 'package:flutter/material.dart';

import '../data/training_catalog.dart';
import '../models/training_plan.dart';
import '../planner/models.dart';
import '../planner/plan_adapter.dart';
import '../planner/plan_copy.dart';
import '../state/plan_controller.dart';
import '../theme/app_colors.dart';
import '../theme/app_text_styles.dart';
import '../widgets/exercise_glyph.dart';

/// 训练 tab, embedded only inside the social module's bottom bar (screen
/// screen-social-feed, node 193:65) — never shown on Home. Shows the plan
/// generated by PlannerGateway when one exists (see main.dart's onboarding
/// flow); falls back to the fixed weekly sample for accounts that predate
/// plan generation.
class TrainingScreen extends StatelessWidget {
  const TrainingScreen({super.key, required this.plan});

  final PlanController plan;

  @override
  Widget build(BuildContext context) {
    final generated = plan.plan;
    final today = generated != null ? dayWorkoutForDate(generated, DateTime.now()) : TrainingCatalog.forDate(DateTime.now());
    final library = generated != null ? exerciseLibraryFromGenerated(generated) : TrainingCatalog.exerciseLibrary;

    return Column(
        children: [
          Padding(
            padding: const EdgeInsets.all(24),
            child: Row(
              children: [Text('训练', style: AppTextStyles.screenTitle)],
            ),
          ),
          Expanded(
            child: ListView(
              padding: const EdgeInsets.symmetric(horizontal: 24),
              children: [
                if (generated != null) ...[
                  _NutritionSummaryCard(plan: generated),
                  const SizedBox(height: 16),
                ],
                Container(
                  padding: const EdgeInsets.all(18),
                  decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(22)),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          Text('今日计划 · ${today.title}', style: AppTextStyles.cardTitle),
                          Container(
                            padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 5),
                            decoration: BoxDecoration(color: AppColors.brandGreen, borderRadius: BorderRadius.circular(10)),
                            child: const Text('今天', style: AppTextStyles.tagLabel),
                          ),
                        ],
                      ),
                      const SizedBox(height: 12),
                      if (today.isRestDay)
                        Text('今天是休息日，好好恢复', style: TextStyle(fontFamily: AppFonts.inter, color: AppColors.textMuted))
                      else
                        for (final ex in today.exercises) _ExerciseRow(exercise: ex),
                    ],
                  ),
                ),
                const SizedBox(height: 20),
                Text('动作库', style: TextStyle(fontFamily: AppFonts.inter, fontWeight: FontWeight.w600, color: AppColors.ink)),
                const SizedBox(height: 10),
                for (final ex in library)
                  Container(
                    margin: const EdgeInsets.only(bottom: 10),
                    padding: const EdgeInsets.all(14),
                    decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(16)),
                    child: _ExerciseRow(exercise: ex, padded: false),
                  ),
                const SizedBox(height: 20),
              ],
            ),
          ),
        ],
    );
  }
}

class _ExerciseRow extends StatelessWidget {
  const _ExerciseRow({required this.exercise, this.padded = true});

  final PlannedExercise exercise;
  final bool padded;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: EdgeInsets.symmetric(vertical: padded ? 6 : 0),
      child: Row(
        children: [
          ExerciseGlyphAvatar(id: exercise.id, name: exercise.name),
          const SizedBox(width: 12),
          Expanded(
            child: Text(
              exercise.name,
              style: padded
                  ? const TextStyle(fontFamily: AppFonts.inter, color: AppColors.ink)
                  : AppTextStyles.cardName,
            ),
          ),
          Text('${exercise.sets} 组 × ${exercise.reps}', style: AppTextStyles.cardMeta),
        ],
      ),
    );
  }
}

class _NutritionSummaryCard extends StatelessWidget {
  const _NutritionSummaryCard({required this.plan});

  final GeneratedPlan plan;

  @override
  Widget build(BuildContext context) {
    final dt = plan.macros.dailyTargets;
    return Container(
      padding: const EdgeInsets.all(18),
      decoration: BoxDecoration(color: AppColors.ink, borderRadius: BorderRadius.circular(22)),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text('每日热量目标', style: TextStyle(fontFamily: AppFonts.inter, fontSize: 13, color: Colors.white.withValues(alpha: 0.6))),
              Text(plan.split.splitName, style: const TextStyle(fontFamily: AppFonts.jetBrainsMono, fontSize: 11, color: AppColors.brandGreen)),
            ],
          ),
          const SizedBox(height: 6),
          Text('${dt['kcal']} kcal', style: const TextStyle(fontFamily: AppFonts.jetBrainsMono, fontWeight: FontWeight.bold, fontSize: 28, color: Colors.white)),
          const SizedBox(height: 10),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              _MacroStat(label: '蛋白质', value: '${dt['protein_g']}g'),
              _MacroStat(label: '脂肪', value: '${dt['fat_g']}g'),
              _MacroStat(label: '碳水', value: '${dt['carbs_g']}g'),
            ],
          ),
          const SizedBox(height: 12),
          Text(
            '第 ${planWeekNumber(plan.generatedAt)} 周 · ${progressionStrategyLabel(plan.progression.strategy)} · ${supplementLine(plan.supplements)}',
            style: TextStyle(fontFamily: AppFonts.inter, fontSize: 11, height: 1.4, color: Colors.white.withValues(alpha: 0.7)),
          ),
        ],
      ),
    );
  }
}

class _MacroStat extends StatelessWidget {
  const _MacroStat({required this.label, required this.value});

  final String label;
  final String value;

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(label, style: TextStyle(fontFamily: AppFonts.inter, fontSize: 11, color: Colors.white.withValues(alpha: 0.6))),
        Text(value, style: const TextStyle(fontFamily: AppFonts.jetBrainsMono, fontWeight: FontWeight.w600, fontSize: 15, color: AppColors.brandGreen)),
      ],
    );
  }
}
